
import './globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script';
import { AuthProvider } from "@/context/AuthContext";
import "@/lib/fontawesome";
import { Toaster } from 'react-hot-toast';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  metadataBase: new URL("https://unisol-sajjad.vercel.app"),
  title: 'Unisol Sajjad CNC Blog',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* ✅ GTM Head Script using next/script */}
        <Script
          id="gtm-head"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
              new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
              j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
              'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','GTM-5QSLDLXL');
            `,
          }}
        />
        <meta name="google-site-verification" content="XJP44XTs6xw1zsn_--eV5LX4ogJhEAZstOF8Nm4EXZk" />
        {/* ✅ Schema.org JSON-LD Structured Data */}
        <Script
          id="schema-org"
          type="application/ld+json"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Organization",
              "name": "Unisol Sajjad CNC",
              "url": "https://unisol-sajjad.vercel.app",
              "logo": "https://unisol-sajjad.vercel.app/sajjad-2d-3d-cnc-dxf-svg.svg", // ✅ اگر لوگو اور ہے تو درست کر لینا
              "description": "Specialized in CNC 2D/3D DXF & SVG designs, high precision artwork for laser cutting and engraving.", // ✅ اپنی مرضی سے اور بہتر کرو
              "address": {
                "@type": "PostalAddress",
                "addressCountry": "PK"
              },
              "contactPoint": {
                "@type": "ContactPoint",
                "telephone": "+92-321-5302092", // ✅ اپنا اصل نمبر لگاؤ
                "contactType": "customer support",
                "availableLanguage": ["English", "Urdu"]
              },
              "sameAs": [
                "https://wa.me/923215302092", // ✅ WhatsApp link درست کرو
                // "https://www.facebook.com/YOUR_PAGE", // ✅ Facebook link لگاؤ
                // "https://www.instagram.com/YOUR_PROFILE" // ✅ Instagram link لگاؤ
              ]
            })
          }}
        />
      </head>
      <body className={inter.className}>
        {/* ✅ GTM noscript fallback */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=GTM-5QSLDLXL"
            height="0"
            width="0"
            style={{ display: 'none', visibility: 'hidden' }}
          ></iframe>
        </noscript>

        <AuthProvider>
          {children}
          <Toaster
            position="top-right"
            toastOptions={{
              duration: 4000,
              style: {
                background: '#363636',
                color: '#fff',
              },
              success: {
                duration: 3000,
                theme: {
                  primary: '#4aed88',
                },
              },
            }}
          />
        </AuthProvider>
      </body>
    </html>
  );
}
